name: deploy to github pages

on:
  push:
    branches:
      - "main"
  pull_request: 
    branches: 
      - "main"
  
  workflow_dispatch:

env:
  BASE: /Todo-app/

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: cloning the repo
        uses: actions/checkout@v4
      
      - name: setting up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Installing dependencies
        run: npm ci
      
      - name: generating build
        env:
          VITE_BASE: ${{ vars.VITE_BASE }}
        run : npm run build
      
      - name: Create .nojekyll to disable Jekyll processing
        run: touch dist/.nojekyll

      - name: Copy index.html to 404.html (Fixes Refresh)
        run: cp dist/index.html dist/404.html

      - name: uploading build folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
